language: objective-c
osx_image: xcode7.3
before_install: true
install: true
git:
  submodules: false
before_script:
  - git submodule update --init --recursive
script:
  - set -o pipefail
  - xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -sdk "$XCODE_SDK" | xcpretty
xcode_workspace: ReactiveCocoa.xcworkspace
matrix:
  include:
    - xcode_scheme: ReactiveCocoa-Mac
      env: XCODE_SDK=macosx
    - xcode_scheme: ReactiveCocoa-iOS
      env: XCODE_SDK=iphonesimulator
notifications:
  email: false
  slack:
    secure: C9QTry5wUG9CfeH3rm3Z19R5rDWqDO7EhHAqHDXBxT6CpGRkTPFliJexpjBYB4sroJ8CiY5ZgTI2sjRBiAdGoE5ZQkfnwSoKQhWXkwo19TnbSnufr3cKO2SZkUhBqOlZcA+mgfjZ7rm2wm7RhpCR/4z8oBXDN4/xv0U5R2fLCLE=
